### ISSUE TITLE
Thermal temperature Fahrenheit setting

### ISSUE THREAD

**Issue by tomm1e** [paradoxxxzero/gnome-shell-system-monitor-applet#344]
Checking "Display temperature in Fahrenheit" updates the number and C to F in the dropdown, but in the status bar it still displays as C.

**Comment by marxin** [comment]
Mine, I'll take a look.

**Comment by marxin** [comment]
Can't reproduce. Please note that after checking the checkbox one has to wait for refresh time before the unit is changed. If that's not the problem, please attach a screenshot.

**Comment by jwhipp** [comment]
I'm on master as of April 18th, here's a screen shot of the issue.

"Display Temperature in Fahrenheit" is checked.   In the bar you see the F temp with a C.   I've been through several reboots and this issue persits.

![selection_003](https://cloud.githubusercontent.com/assets/556332/25191406/b8f5873e-24ec-11e7-9eba-101d102c9012.png)

**Comment by franglais125** [comment]
I fixed this in [e7f3c41ad03888a0df6c9d25c33f52a842ac0368].

**Comment by franglais125** [comment]
@jwhipp @eimmot Could you test the fix I mentioned? Just to confirm that it works.

**Comment by eimmot** [comment]
The top bar symbol label still doesn't change when checking/unchecking the setting

**Comment by franglais125** [comment]
@eimmot you need to apply the patch I mentioned, turn on the Fahrenheit option, **and** restart the session.

Toggling to setting is not interactive, we'd need to apply more changes for that, and I;m trying to keep things simple.

**Comment by enebo** [comment]
@franglais125 is a release with this fix going to be pushed to gnome extensions site any time soon.  I do not think it has been released yet right?

**Comment by franglais125** [comment]
@enebo I hope so, but I'm not the maintainer of the extension. It's up to @chrisspen to do that.
